rust_library(
    name = "dyld",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2021",
    deps = [
        "third-party//:goblin",
        "third-party//:spin",
        "third-party//:bitflags",
        "third-party//:linked_list_allocator",
    ],
    visibility = ["PUBLIC"],
)
