rust_binary(
    name = "ipsw",
    srcs = glob(["**/*.rs"]),
    crate_root = "main.rs",
    edition = "2024",
    deps = [
        "third-party//:reqwest",
        "third-party//:plist",
        "third-party//:serde",
        "third-party//:thiserror",
        "third-party//:tokio",
        "//src/lib/vfdecrypt:vfdecrypt",
        "//src/lib/ipsw-downloader:ipsw-downloader",
        "third-party//:indicatif",
        "third-party//:clap",
    ],
    visibility = ["PUBLIC"],
)
