rust_library(
    name = "ipsw-downloader",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "third-party//:reqwest",
        "third-party//:plist",
        "third-party//:serde",
        "third-party//:thiserror",
        "third-party//:tokio",
    ],
    visibility = ["PUBLIC"],
)
